# frpc.toml
serverAddr = "{{ .Envs.FRP_SERVER_ADDR }}"
serverPort = {{ .Envs.FRP_SERVER_PORT }}

[[proxies]]
name = "serv"
type = "tcp"
localIP = "{{ .Envs.FRP_LOCAL_SERVICE_ADDR }}"
localPort = "{{ .Envs.FRP_LOCAL_SERVICE_PORT }}"
remotePort = "{{ .Envs.FRP_REMOTE_PORT }}"
